CREATE TABLE `uro_package` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `chinese_name` varchar(100) NOT NULL DEFAULT '' COMMENT '中文名称',
  `show_name` varchar(100) NOT NULL DEFAULT '' COMMENT '显示名称(当地语言)',
  `price` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '价格，单位分',
  `days` int(11) NOT NULL DEFAULT '1' COMMENT '套餐天数',
  `extra_daily_price` decimal(6,2) NOT NULL DEFAULT '0.00' COMMENT '超出日租金',
  `status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '状态，1正常，0暂停',
  `currency_unit` varchar(6) NOT NULL DEFAULT '' COMMENT '货币单位，取country表中与sale_country_id对应的国家的单位',
  `sale_country_id` int(11) NOT NULL DEFAULT '0' COMMENT '业务办理国家id',
  `traffic_limit` int(11) NOT NULL DEFAULT '0' COMMENT '限流，单位M，0不限',
  `extra_traffic_price` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '超出价',
  `min_rent_days` int(11) NOT NULL DEFAULT '0' COMMENT '起租天数，0未设置',
  `deposit` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '押金',
  `create_uid` int(11) NOT NULL DEFAULT '0' COMMENT '创建用户的uid',
  `created_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_uid` int(11) NOT NULL DEFAULT '0' COMMENT '修改用户的uid',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `network_speed` varchar(255) NOT NULL DEFAULT '0' COMMENT '网速,单位k',
  `summary` varchar(255) NOT NULL DEFAULT '' COMMENT '简介',
  `pic` varchar(100) NOT NULL DEFAULT '' COMMENT '图片',
  `service_info` text COMMENT '服务介绍',
  `sort` int(11) NOT NULL DEFAULT '0' COMMENT '排序',
  `daily_price` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT '日单价',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=13 DEFAULT CHARSET=utf8 COMMENT='套餐表'
